// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentMarksheet.DataAccess;

#nullable disable

namespace StudentMarksheet.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentMarksheet.Model.Marks", b =>
                {
                    b.Property<string>("RollNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Chemistry")
                        .HasColumnType("int");

                    b.Property<int>("Maths")
                        .HasColumnType("int");

                    b.Property<int>("Physics")
                        .HasColumnType("int");

                    b.Property<int>("SecondLanguage")
                        .HasColumnType("int");

                    b.Property<int>("SocialStudies")
                        .HasColumnType("int");

                    b.HasKey("RollNumber");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("StudentMarksheet.Model.StudentMarksEntity", b =>
                {
                    b.Property<string>("RollNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("int");

                    b.HasKey("RollNumber");

                    b.ToTable("StudentMarks");
                });

            modelBuilder.Entity("StudentMarksheet.Model.Marks", b =>
                {
                    b.HasOne("StudentMarksheet.Model.StudentMarksEntity", "Student")
                        .WithOne("Marks")
                        .HasForeignKey("StudentMarksheet.Model.Marks", "RollNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentMarksheet.Model.StudentMarksEntity", b =>
                {
                    b.Navigation("Marks")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
